### PR TITLE
Make use of the new option "TensorPreservesEpis"

### PR DESCRIPTION
**Pull request by zickgraf**
See commit messages for details.

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
I probably need to wait until the version bumps are merged in CAP, right? I, therefore, suggest increasing versions of packages within the commit fixing the bug or introducing new features. Please also increase the version of this package accordingly.

**Comment by zickgraf** [comment]
You are right, I forgot to bump the version in my original CAP PR, sorry for the noise. I have bumped the version of this package now and will convert this PR to a draft until the version bumps are merged in CAP. Then (hopefully) everything should be consistent again! :-)

**Comment by zickgraf** [comment]
This is ready for review/merge.

**Comment by mohamed-barakat** [comment]
Thanks :)

**Pull request merged**
